##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
version: '2'
services:
  opnfv-fuel-salt-master:
    container_name: "fuel"
    image: "opnfv/fuel:saltmaster-reclass-latest"
    restart: always
    networks:
      mcpcontrol:
        ipv4_address: 10.20.0.2
      pxebr:
        ipv4_address: 192.168.11.2
      mgmt:
        ipv4_address: 172.16.10.11
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
      - /home/opnfv/fuel:/root/fuel
      - /home/opnfv/fuel/mcp/scripts/docker-compose/files/entrypoint.sh:/entrypoint.sh
      - /home/opnfv/tmpdir/pod_config.yml:/root/pod_config.yml
      - /home/opnfv/tmpdir/nodes:/srv/salt/reclass/nodes
      - /home/opnfv/tmpdir/pki:/etc/pki
      - /home/opnfv/tmpdir/salt:/etc/salt
      - /home/opnfv/tmpdir/hosts:/etc/hosts
    hostname: cfg01
    domainname: mcp-odl-noha.local
    privileged: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
networks:
  mcpcontrol:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000
    ipam:
      config:
        - subnet: 10.20.0.0/24
  pxebr:
    driver: macvlan
    driver_opts:
      parent: veth_mcp1  # Always untagged
    ipam:
      config:
        - subnet: 192.168.11.0/24
  mgmt:
    driver: macvlan
    driver_opts:
      parent: veth_mcp3  # Untagged by default
    ipam:
      config:
        - subnet: 172.16.10.0/24