##############################################################################
# Copyright (c) 2019 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - system.reclass.storage.salt
  - system.reclass.storage.system.kubernetes_control_single
  - system.salt.master.api
  - system.salt.master.single
  - system.salt.minion.ca.salt_master
  - system.salt.minion.cert.k8s_server_single
  - cluster.mcp-k8s-calico-noha
parameters:
  _param:
    salt_master_environment_repository: 'https://github.com/salt-formulas'
    salt_master_environment_revision: master
    reclass_data_repository: local
    salt_master_base_environment: prd
    salt_master_host: 127.0.0.1
    salt_minion_ca_host: ${linux:network:fqdn}
    # yamllint disable-line rule:line-length
    salt_api_password_hash: "$6$sGnRlxGf$al5jMCetLP.vfI/fTl3Z0N7Za1aeiexL487jAtyRABVfT3NlwZxQGVhO7S1N8OwS/34VHYwZQA8lkXwKMN/GS1"
    kubernetes_control_node01_deploy_address: ${_param:opnfv_openstack_control_node01_pxe_admin_address}
    kubernetes_control_system_codename: bionic
  linux:
    system:
      user:
        salt:
          home: /home/salt
  salt:
    master:
      accept_policy: open_mode
      file_recv: true
      worker_threads: 4
      command_timeout: 20
    minion:
      mine:
        module:
          x509.get_pem_entries: ['/etc/pki/all_cas/*']
  reclass:
    storage:
      data_source:
        engine: local
      node:
        kubernetes_control_node01:
          params:
            pxe_admin_interface: ens3
            pxe_admin_address: ${_param:opnfv_openstack_control_node01_pxe_admin_address}
        # We support per-node (not only per-role) compute configuration via IDF
        kubernetes_compute_node01:
          name: cmp001
          domain: ${_param:cluster_domain}
          classes:
            - cluster.${_param:cluster_name}.kubernetes.compute
          params:
            pxe_admin_address: 192.168.11.36
            pxe_admin_interface: ens3
            single_address: 172.16.10.55
            tenant_address: 10.1.0.5
            external_address: 10.16.0.111
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: ${_param:kubernetes_control_system_codename}
        kubernetes_compute_node02:
          name: cmp002
          domain: ${_param:cluster_domain}
          classes:
            - cluster.${_param:cluster_name}.kubernetes.compute
          params:
            pxe_admin_address: 192.168.11.37
            pxe_admin_interface: ens3
            single_address: 172.16.10.56
            tenant_address: 10.1.0.6
            external_address: 10.16.0.112
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: ${_param:kubernetes_control_system_codename}