##############################################################################
# Copyright (c) 2019 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - system.salt.control.virt
  - cluster.all-mcp-arch-common.opnfv.maas_proxy
  - cluster.all-mcp-arch-common.opnfv.lab_proxy_pdf
  - cluster.mcp-iec-noha.infra
parameters:
  _param:
    linux_system_codename: bionic
  linux:
    network:
      interface:


        ens4:
          enabled: true
          type: eth
          proto: manual
          mtu: ${_param:interface_mtu}
          name: ens4
          noifupdown: true
        ens6:
          enabled: true
          type: eth
          proto: manual
          mtu: ${_param:interface_mtu}
          name: ens6
          noifupdown: true
        ens3:
          enabled: true
          type: eth
          proto: manual
          mtu: ${_param:interface_mtu}
          name: ens3
          noifupdown: true



        br-mgmt:
          enabled: true
          proto: static
          address: ${_param:pxe_admin_address}
          netmask: ${_param:opnfv_net_admin_mask}
          gateway: 192.168.11.3
          name_servers:
            - 192.168.11.3
          type: bridge
          use_interfaces:
            - ens3
          noifupdown: true
        br-ctl:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:single_address}
          netmask: ${_param:opnfv_net_mgmt_mask}
          use_interfaces:
            - ens4
          noifupdown: true
        br-ex:
          enabled: true
          proto: manual
          netmask: ${_param:opnfv_net_public_mask}
          type: bridge
          use_interfaces:
            - ens6
          noifupdown: true
    system:
      kernel:
        boot_options:
          - spectre_v2=off
          - nopti
          - kpti=off
        sysctl:
          net.ipv4.ip_forward: 0
  libvirt:
    server:
      service: libvirtd
      config_sys: /etc/default/libvirtd
      unix_sock_group: libvirt
  salt:
    control:
      size:
        akraino.iec:
          cpu: 8
          ram: 12288
          disk_profile: small
          net_profile: default
      cluster:
        internal:
          domain: ${_param:cluster_domain}
          engine: virt
          node:
            iec01:
              name: ${_param:akraino_iec_node01_hostname}
              provider: ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
              size: akraino.iec
              image: ${_param:salt_control_bionic_image}
            iec02:
              name: ${_param:akraino_iec_node02_hostname}
              provider: ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
              size: akraino.iec
              image: ${_param:salt_control_bionic_image}
            iec03:
              name: ${_param:akraino_iec_node03_hostname}
              provider: ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
              size: akraino.iec
              image: ${_param:salt_control_bionic_image}
  virt:
    nic:
      default:
        eth2:
          bridge: br-mgmt
          model: virtio
        eth1:
          bridge: br-ex
          model: virtio
        eth0:
          bridge: br-ctl
          model: virtio